python mergeSummariesS.py 1 1 0
python mergeSummariesS.py 1 1 1
python mergeSummariesS.py 1 1 2
python mergeSummariesS.py 1 1 3
python mergeSummariesS.py 1 1 4
python mergeSummariesS.py 1 1 5
python mergeSummariesS.py 1 2 0
python mergeSummariesS.py 1 2 1
python mergeSummariesS.py 1 2 2
python mergeSummariesS.py 1 2 3
python mergeSummariesS.py 1 2 4
python mergeSummariesS.py 1 2 5
python mergeSummariesS.py 1 3 0
python mergeSummariesS.py 1 3 1
python mergeSummariesS.py 1 3 2
python mergeSummariesS.py 1 3 3
python mergeSummariesS.py 1 3 4
python mergeSummariesS.py 1 3 5
python mergeSummariesS.py 3 1 0
python mergeSummariesS.py 3 1 1
python mergeSummariesS.py 3 1 2
python mergeSummariesS.py 3 1 3
python mergeSummariesS.py 3 1 4
python mergeSummariesS.py 3 1 5
python mergeSummariesS.py 3 2 0
python mergeSummariesS.py 3 2 1
python mergeSummariesS.py 3 2 2
python mergeSummariesS.py 3 2 3
python mergeSummariesS.py 3 2 4
python mergeSummariesS.py 3 2 5
python mergeSummariesS.py 3 3 0
python mergeSummariesS.py 3 3 1
python mergeSummariesS.py 3 3 2
python mergeSummariesS.py 3 3 3
python mergeSummariesS.py 3 3 4
python mergeSummariesS.py 3 3 5
python mergeSummariesS.py 4 1 0
python mergeSummariesS.py 4 1 1
python mergeSummariesS.py 4 1 2
python mergeSummariesS.py 4 1 3
python mergeSummariesS.py 4 1 4
python mergeSummariesS.py 4 1 5
python mergeSummariesS.py 4 1 6
python mergeSummariesS.py 4 1 7
python mergeSummariesS.py 4 1 8
python mergeSummariesS.py 4 1 9
python mergeSummariesS.py 4 2 0
python mergeSummariesS.py 4 2 1
python mergeSummariesS.py 4 2 2
python mergeSummariesS.py 4 2 3
python mergeSummariesS.py 4 2 4
python mergeSummariesS.py 4 2 5
python mergeSummariesS.py 4 2 6
python mergeSummariesS.py 4 2 7
python mergeSummariesS.py 4 2 8
python mergeSummariesS.py 4 2 9
python mergeSummariesS.py 4 3 0
python mergeSummariesS.py 4 3 1
python mergeSummariesS.py 4 3 2
python mergeSummariesS.py 4 3 3
python mergeSummariesS.py 4 3 4
python mergeSummariesS.py 4 3 5
python mergeSummariesS.py 4 3 6
python mergeSummariesS.py 4 3 7
python mergeSummariesS.py 4 3 8
python mergeSummariesS.py 4 3 9
python mergeSummariesS.py 2 1 0
python mergeSummariesS.py 2 1 1
python mergeSummariesS.py 2 1 2
python mergeSummariesS.py 2 1 3
python mergeSummariesS.py 2 1 4
python mergeSummariesS.py 2 1 5
python mergeSummariesS.py 2 2 0
python mergeSummariesS.py 2 2 1
python mergeSummariesS.py 2 2 2
python mergeSummariesS.py 2 2 3
python mergeSummariesS.py 2 2 4
python mergeSummariesS.py 2 2 5
python mergeSummariesS.py 2 3 0
python mergeSummariesS.py 2 3 1
python mergeSummariesS.py 2 3 2
python mergeSummariesS.py 2 3 3
python mergeSummariesS.py 2 3 4
python mergeSummariesS.py 2 3 5